config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :articles do
    resources :histories
  end
  # resources :users, only: [:index, :show]
  
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  attr_accessor :default_content#, :original_updated_at
  belongs_to :category
  has_many   :histories, dependent: :destroy

  validates :title,             presence: true
  validates :category_id,       presence: true
  # validates :latest_version_id, presence: true
  # validate :handle_conflict,    on: :update

  def content
    latest_version.present? ? latest_version.content : default_content
  end

  def update_comment
  end

  def latest_version
    # @latest_version ||= histories.last
    @latest_version ||= History.where(id: latest_version_id).first
  end

  # def default_content
  #   "在此输入文章内容"
  # end

  # # 发生改变的是history 所以应该在history上加乐观锁
  # def original_updated_at
  #   @original_updated_at ||= updated_at.to_f
  # end

  # def handle_conflict
  #   # updated_at的时间并不是这次更新的时间，而是数据库中的update_at值。
  #   # 此时还没有update成功，所以这个判断是无效的
  #   if updated_at.to_f > original_updated_at
  #     @conflict = true
  #     @original_updated_at = nil
  #     self.errors.add(:base, "该文章在编辑时已被其他用户修改，请保存您的修改再次尝试")
  #   end
  # end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :article
  # belongs_to :editor

  validates :article_id, presence: true
  # validates :editor_id,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :load_sidebar
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def load_sidebar
    @sidebar_categories = Category.all
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article_and_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order("category_id asc")
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        update_history_and_latestversionid
        flash[:success] = "新文章已保存"
        format.html { redirect_to @article }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        update_history_and_latestversionid
        flash[:success] = "修改保存成功"
        format.html { redirect_to @article }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      flash[:success] = "文章已删除"
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_and_category
      @article = Article.find(params[:id])
      @category = @article.category
    end

    def update_history_and_latestversionid
      history = @article.histories.create!({
        # editor: current_user
        content:   params.require(:article)[:content], 
        comment:   params.require(:article)[:update_comment],
        editor_id: current_user.id
      })
      @article.update(latest_version_id: history.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :category_id, :original_history_version_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def show
    @category = Category.find_by(id: params[:id])
    @articles = @category.articles
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  def index
    @article = Article.find(params[:article_id])
    @histories = @article.histories.order(created_at: :desc)
  end

  def show
    @article = @history.article
  end

  private
    def set_history
      @history = History.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_bootstrap_views_helper.rb
module DeviseHelper
  # def bootstrap_devise_error_messages!
  #   return '' if resource.errors.empty?

  #   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
  #   sentence = I18n.t('errors.messages.not_saved',
  #   count: resource.errors.count,
  #   resource: resource.class.model_name.human.downcase)

  #   html = <<-HTML
  #     <div class="alert alert-danger alert-block"> <button type="button"
  #     class="close" data-dismiss="alert">x</button>
  #     <h4>#{sentence}</h4>
  #     #{messages}
  #     </div>
  #   HTML

  #   html.html_safe
  # end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :标题 %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :分类 %>
    <%= f.collection_select :category_id, Category.all, :id, :name, { promt: "请选择文章分类" } %>
  </div>

  <div class="field">
    <%= f.label :内容 %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :更新内容 %>
    <%= f.text_area :update_comment %>
  </div>

  <div class="actions">
    <%= f.submit "保存文章", class: "btn btn-primary", id: "save_btn" %>
  </div>
<% end %>

<script type="text/javascript">
  var editor = new Simditor({
    textarea: $('#article_content'),
    placeholder: 'enter text here...',
    toolbar: ['title', 'bold', 'italic', 'underline', 'strikethrough', 'fontScale', 'color', '|', 'ol', 'ul', '|', 'blockquote', 'code', 'table', 'link', 'image', 'hr', 'indent', 'outdent', 'alignment']
    //optional options
  });
</script>

app/views/articles/edit.html.erb
<h1>编辑文章</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', category_path(@category) %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to "#{article.title}", article %></td>
        <td><%= strip_tags(article.content[0, 40]) %></td>
        <td><%= link_to '编辑', edit_article_path(article) %></td>
        <td><%= link_to '删除', article, method: :delete, data: { confirm: "确定要删除文章：#{article.title} 吗？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>新文章</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1><%= @article.title %></h1>

<hr>

<div><%= raw(@article.content) %></div>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', category_path(@category) %> |
<%= link_to '查看历史', article_histories_path(@article) %>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/new.html.erb
<h1>新建分类</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', root_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @category.name %></h1>

<table>
  <thead>
    <tr>
      <th>标题</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to "#{article.title}", article %></td>
        <td><%= strip_tags(article.content[0, 40]) %></td>
        <td><%= link_to '编辑', edit_article_path(article) %></td>
        <td><%= link_to '查看历史', article_histories_path(article) %></td>
        <td><%= link_to '删除', article, method: :delete, data: { confirm: "确定要删除文章：#{article.title} 吗？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/histories/index.html.erb
<h1>“<%= @article.title %>”的版本历史</h1>

<table>
  <thead>
    <tr>
      <th>更新时间</th>
      <th>内容</th>
      <th>更新日志</th>
      <th>编辑者</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= link_to "#{history.created_at}", article_history_path(@article, history) %></td>
        <td><%= strip_tags(history.content[0, 40]) %></td>
        <td><%= history.comment %></td>
        <td><%= link_to "#{User.find(history.editor_id).username}", '#' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/histories/show.html.erb
<h1>“<%= @article.title %>”的版本历史</h1>
<p>创建于：<%= @history.created_at %></p>

<hr>

<div><%= raw(@history.content) %></div>

app/views/layouts/_alert.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "alert" %>
    <%= content_tag(:div, message, class: "alert alert-danger") %>
  <% elsif message_type == "notice" %>
    <%= content_tag(:div, message, class: "alert alert-success") %>
  <% else %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <hr>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id="header">
  <div class="container">
    <%= link_to "T7S 中文WIKI", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right" id="header_nav" >
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   '#'%></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", '#' %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "login",  new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<% @sidebar_categories.each do |category| %>
  <ul><%= link_to "#{category.name}", category %></ul>
    <% for article in category.articles %>
      <li><%= link_to "#{article.title}", article %></li>
    <% end %>
<% end %>
<ul><%= link_to "新建分类", new_category_path %></ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T7Scn</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="body">
      <div class="row">
        <!-- <h1>T7S中文Wiki</h1> -->
        <div class="col-md-3 sidebar">
          <%= render 'layouts/sidebar' %>
        </div>
        <div class="col-md-9">
          <%= render 'layouts/alert' %>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
  <%= debug(params) if Rails.env.development? %>
</html>